/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>additive expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.additive_expression#getMultiplicative_expression <em>Multiplicative expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.additive_expression#getAdditive_expression2 <em>Additive expression2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression()
 * @model
 * @generated
 */
public interface additive_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Multiplicative expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multiplicative expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicative expression</em>' containment reference.
   * @see #setMultiplicative_expression(multiplicative_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_Multiplicative_expression()
   * @model containment="true"
   * @generated
   */
  multiplicative_expression getMultiplicative_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.additive_expression#getMultiplicative_expression <em>Multiplicative expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicative expression</em>' containment reference.
   * @see #getMultiplicative_expression()
   * @generated
   */
  void setMultiplicative_expression(multiplicative_expression value);

  /**
   * Returns the value of the '<em><b>Additive expression2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Additive expression2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additive expression2</em>' containment reference.
   * @see #setAdditive_expression2(additive_expression2)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_Additive_expression2()
   * @model containment="true"
   * @generated
   */
  additive_expression2 getAdditive_expression2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.additive_expression#getAdditive_expression2 <em>Additive expression2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additive expression2</em>' containment reference.
   * @see #getAdditive_expression2()
   * @generated
   */
  void setAdditive_expression2(additive_expression2 value);

} // additive_expression
