/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>char Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.charType#getChar_type <em>Char type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getcharType()
 * @model
 * @generated
 */
public interface charType extends type_specifier
{
  /**
   * Returns the value of the '<em><b>Char type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Char type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Char type</em>' attribute.
   * @see #setChar_type(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getcharType_Char_type()
   * @model
   * @generated
   */
  String getChar_type();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.charType#getChar_type <em>Char type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Char type</em>' attribute.
   * @see #getChar_type()
   * @generated
   */
  void setChar_type(String value);

} // charType
