/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>declaration list2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.declaration_list2#getDeclaration <em>Declaration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.declaration_list2#getDeclaration_list2 <em>Declaration list2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclaration_list2()
 * @model
 * @generated
 */
public interface declaration_list2 extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(declaration)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclaration_list2_Declaration()
   * @model containment="true"
   * @generated
   */
  declaration getDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.declaration_list2#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(declaration value);

  /**
   * Returns the value of the '<em><b>Declaration list2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration list2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration list2</em>' containment reference.
   * @see #setDeclaration_list2(declaration_list2)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclaration_list2_Declaration_list2()
   * @model containment="true"
   * @generated
   */
  declaration_list2 getDeclaration_list2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.declaration_list2#getDeclaration_list2 <em>Declaration list2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration list2</em>' containment reference.
   * @see #getDeclaration_list2()
   * @generated
   */
  void setDeclaration_list2(declaration_list2 value);

} // declaration_list2
