/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>generic assoc list</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.generic_assoc_list#getGeneric_association <em>Generic association</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.generic_assoc_list#getGeneric_list <em>Generic list</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getgeneric_assoc_list()
 * @model
 * @generated
 */
public interface generic_assoc_list extends EObject
{
  /**
   * Returns the value of the '<em><b>Generic association</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Generic association</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic association</em>' containment reference.
   * @see #setGeneric_association(generic_association)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getgeneric_assoc_list_Generic_association()
   * @model containment="true"
   * @generated
   */
  generic_association getGeneric_association();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.generic_assoc_list#getGeneric_association <em>Generic association</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generic association</em>' containment reference.
   * @see #getGeneric_association()
   * @generated
   */
  void setGeneric_association(generic_association value);

  /**
   * Returns the value of the '<em><b>Generic list</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.generic_association}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Generic list</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic list</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getgeneric_assoc_list_Generic_list()
   * @model containment="true"
   * @generated
   */
  EList<generic_association> getGeneric_list();

} // generic_assoc_list
