/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>integer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.integer#getInt_type <em>Int type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinteger()
 * @model
 * @generated
 */
public interface integer extends type_specifier
{
  /**
   * Returns the value of the '<em><b>Int type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int type</em>' attribute.
   * @see #setInt_type(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinteger_Int_type()
   * @model
   * @generated
   */
  String getInt_type();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.integer#getInt_type <em>Int type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int type</em>' attribute.
   * @see #getInt_type()
   * @generated
   */
  void setInt_type(String value);

} // integer
