/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>parameter list2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.parameter_list2#getParameter_declaration <em>Parameter declaration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.parameter_list2#getParameter_list2 <em>Parameter list2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_list2()
 * @model
 * @generated
 */
public interface parameter_list2 extends EObject
{
  /**
   * Returns the value of the '<em><b>Parameter declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter declaration</em>' containment reference.
   * @see #setParameter_declaration(parameter_declaration)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_list2_Parameter_declaration()
   * @model containment="true"
   * @generated
   */
  parameter_declaration getParameter_declaration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.parameter_list2#getParameter_declaration <em>Parameter declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter declaration</em>' containment reference.
   * @see #getParameter_declaration()
   * @generated
   */
  void setParameter_declaration(parameter_declaration value);

  /**
   * Returns the value of the '<em><b>Parameter list2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter list2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter list2</em>' containment reference.
   * @see #setParameter_list2(parameter_list2)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_list2_Parameter_list2()
   * @model containment="true"
   * @generated
   */
  parameter_list2 getParameter_list2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.parameter_list2#getParameter_list2 <em>Parameter list2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter list2</em>' containment reference.
   * @see #getParameter_list2()
   * @generated
   */
  void setParameter_list2(parameter_list2 value);

} // parameter_list2
