/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>postfix expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.postfix_expression#getPrimary_expression <em>Primary expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.postfix_expression#getPostfix_expression2 <em>Postfix expression2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.postfix_expression#getType_name <em>Type name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.postfix_expression#getInitializer_list <em>Initializer list</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expression()
 * @model
 * @generated
 */
public interface postfix_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Primary expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primary expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary expression</em>' containment reference.
   * @see #setPrimary_expression(primary_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expression_Primary_expression()
   * @model containment="true"
   * @generated
   */
  primary_expression getPrimary_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.postfix_expression#getPrimary_expression <em>Primary expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary expression</em>' containment reference.
   * @see #getPrimary_expression()
   * @generated
   */
  void setPrimary_expression(primary_expression value);

  /**
   * Returns the value of the '<em><b>Postfix expression2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Postfix expression2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postfix expression2</em>' containment reference.
   * @see #setPostfix_expression2(postfix_expression2)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expression_Postfix_expression2()
   * @model containment="true"
   * @generated
   */
  postfix_expression2 getPostfix_expression2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.postfix_expression#getPostfix_expression2 <em>Postfix expression2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Postfix expression2</em>' containment reference.
   * @see #getPostfix_expression2()
   * @generated
   */
  void setPostfix_expression2(postfix_expression2 value);

  /**
   * Returns the value of the '<em><b>Type name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type name</em>' containment reference.
   * @see #setType_name(type_name)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expression_Type_name()
   * @model containment="true"
   * @generated
   */
  type_name getType_name();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.postfix_expression#getType_name <em>Type name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type name</em>' containment reference.
   * @see #getType_name()
   * @generated
   */
  void setType_name(type_name value);

  /**
   * Returns the value of the '<em><b>Initializer list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initializer list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initializer list</em>' containment reference.
   * @see #setInitializer_list(initializer_list)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expression_Initializer_list()
   * @model containment="true"
   * @generated
   */
  initializer_list getInitializer_list();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.postfix_expression#getInitializer_list <em>Initializer list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initializer list</em>' containment reference.
   * @see #getInitializer_list()
   * @generated
   */
  void setInitializer_list(initializer_list value);

} // postfix_expression
