/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>short Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.shortType#getShort_type <em>Short type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getshortType()
 * @model
 * @generated
 */
public interface shortType extends type_specifier
{
  /**
   * Returns the value of the '<em><b>Short type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Short type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short type</em>' attribute.
   * @see #setShort_type(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getshortType_Short_type()
   * @model
   * @generated
   */
  String getShort_type();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.shortType#getShort_type <em>Short type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Short type</em>' attribute.
   * @see #getShort_type()
   * @generated
   */
  void setShort_type(String value);

} // shortType
