/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>static assert declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.static_assert_declaration#getStatic_assert <em>Static assert</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.static_assert_declaration#getConstant_expression <em>Constant expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.static_assert_declaration#getString_literal <em>String literal</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatic_assert_declaration()
 * @model
 * @generated
 */
public interface static_assert_declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Static assert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Static assert</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Static assert</em>' attribute.
   * @see #setStatic_assert(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatic_assert_declaration_Static_assert()
   * @model
   * @generated
   */
  String getStatic_assert();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.static_assert_declaration#getStatic_assert <em>Static assert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Static assert</em>' attribute.
   * @see #getStatic_assert()
   * @generated
   */
  void setStatic_assert(String value);

  /**
   * Returns the value of the '<em><b>Constant expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant expression</em>' containment reference.
   * @see #setConstant_expression(constant_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatic_assert_declaration_Constant_expression()
   * @model containment="true"
   * @generated
   */
  constant_expression getConstant_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.static_assert_declaration#getConstant_expression <em>Constant expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant expression</em>' containment reference.
   * @see #getConstant_expression()
   * @generated
   */
  void setConstant_expression(constant_expression value);

  /**
   * Returns the value of the '<em><b>String literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String literal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String literal</em>' attribute.
   * @see #setString_literal(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatic_assert_declaration_String_literal()
   * @model
   * @generated
   */
  String getString_literal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.static_assert_declaration#getString_literal <em>String literal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String literal</em>' attribute.
   * @see #getString_literal()
   * @generated
   */
  void setString_literal(String value);

} // static_assert_declaration
