/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unary expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getPostfix_expression <em>Postfix expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getInc_op <em>Inc op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getUnary_expression <em>Unary expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getDec_op <em>Dec op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getUnary_operator <em>Unary operator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getCast_expression <em>Cast expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getSizeof <em>Sizeof</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getType_name <em>Type name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unary_expression#getAlignof <em>Alignof</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression()
 * @model
 * @generated
 */
public interface unary_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Postfix expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Postfix expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postfix expression</em>' containment reference.
   * @see #setPostfix_expression(postfix_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Postfix_expression()
   * @model containment="true"
   * @generated
   */
  postfix_expression getPostfix_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getPostfix_expression <em>Postfix expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Postfix expression</em>' containment reference.
   * @see #getPostfix_expression()
   * @generated
   */
  void setPostfix_expression(postfix_expression value);

  /**
   * Returns the value of the '<em><b>Inc op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inc op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inc op</em>' attribute.
   * @see #setInc_op(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Inc_op()
   * @model
   * @generated
   */
  String getInc_op();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getInc_op <em>Inc op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inc op</em>' attribute.
   * @see #getInc_op()
   * @generated
   */
  void setInc_op(String value);

  /**
   * Returns the value of the '<em><b>Unary expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unary expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary expression</em>' containment reference.
   * @see #setUnary_expression(unary_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Unary_expression()
   * @model containment="true"
   * @generated
   */
  unary_expression getUnary_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getUnary_expression <em>Unary expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary expression</em>' containment reference.
   * @see #getUnary_expression()
   * @generated
   */
  void setUnary_expression(unary_expression value);

  /**
   * Returns the value of the '<em><b>Dec op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dec op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec op</em>' attribute.
   * @see #setDec_op(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Dec_op()
   * @model
   * @generated
   */
  String getDec_op();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getDec_op <em>Dec op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec op</em>' attribute.
   * @see #getDec_op()
   * @generated
   */
  void setDec_op(String value);

  /**
   * Returns the value of the '<em><b>Unary operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unary operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary operator</em>' attribute.
   * @see #setUnary_operator(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Unary_operator()
   * @model
   * @generated
   */
  String getUnary_operator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getUnary_operator <em>Unary operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary operator</em>' attribute.
   * @see #getUnary_operator()
   * @generated
   */
  void setUnary_operator(String value);

  /**
   * Returns the value of the '<em><b>Cast expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cast expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cast expression</em>' containment reference.
   * @see #setCast_expression(cast_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Cast_expression()
   * @model containment="true"
   * @generated
   */
  cast_expression getCast_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getCast_expression <em>Cast expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cast expression</em>' containment reference.
   * @see #getCast_expression()
   * @generated
   */
  void setCast_expression(cast_expression value);

  /**
   * Returns the value of the '<em><b>Sizeof</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sizeof</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sizeof</em>' attribute.
   * @see #setSizeof(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Sizeof()
   * @model
   * @generated
   */
  String getSizeof();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getSizeof <em>Sizeof</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sizeof</em>' attribute.
   * @see #getSizeof()
   * @generated
   */
  void setSizeof(String value);

  /**
   * Returns the value of the '<em><b>Type name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type name</em>' containment reference.
   * @see #setType_name(type_name)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Type_name()
   * @model containment="true"
   * @generated
   */
  type_name getType_name();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getType_name <em>Type name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type name</em>' containment reference.
   * @see #getType_name()
   * @generated
   */
  void setType_name(type_name value);

  /**
   * Returns the value of the '<em><b>Alignof</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alignof</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alignof</em>' attribute.
   * @see #setAlignof(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunary_expression_Alignof()
   * @model
   * @generated
   */
  String getAlignof();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unary_expression#getAlignof <em>Alignof</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alignof</em>' attribute.
   * @see #getAlignof()
   * @generated
   */
  void setAlignof(String value);

} // unary_expression
