/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>void Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.voidType#getVoid_type <em>Void type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getvoidType()
 * @model
 * @generated
 */
public interface voidType extends type_specifier
{
  /**
   * Returns the value of the '<em><b>Void type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Void type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Void type</em>' attribute.
   * @see #setVoid_type(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getvoidType_Void_type()
   * @model
   * @generated
   */
  String getVoid_type();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.voidType#getVoid_type <em>Void type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Void type</em>' attribute.
   * @see #getVoid_type()
   * @generated
   */
  void setVoid_type(String value);

} // voidType
