/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.conditional_expression;
import org.xtext.example.mydsl.myDsl.expression;
import org.xtext.example.mydsl.myDsl.simple_expression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>conditional expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.conditional_expressionImpl#getSimple_expression <em>Simple expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.conditional_expressionImpl#getLogical_or_expression <em>Logical or expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.conditional_expressionImpl#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.conditional_expressionImpl#getConditional_expression <em>Conditional expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class conditional_expressionImpl extends MinimalEObjectImpl.Container implements conditional_expression
{
  /**
   * The cached value of the '{@link #getSimple_expression() <em>Simple expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimple_expression()
   * @generated
   * @ordered
   */
  protected simple_expression simple_expression;

  /**
   * The cached value of the '{@link #getLogical_or_expression() <em>Logical or expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLogical_or_expression()
   * @generated
   * @ordered
   */
  protected simple_expression logical_or_expression;

  /**
   * The cached value of the '{@link #getExpression() <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression()
   * @generated
   * @ordered
   */
  protected expression expression;

  /**
   * The cached value of the '{@link #getConditional_expression() <em>Conditional expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditional_expression()
   * @generated
   * @ordered
   */
  protected conditional_expression conditional_expression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected conditional_expressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CONDITIONAL_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public simple_expression getSimple_expression()
  {
    return simple_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSimple_expression(simple_expression newSimple_expression, NotificationChain msgs)
  {
    simple_expression oldSimple_expression = simple_expression;
    simple_expression = newSimple_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION, oldSimple_expression, newSimple_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSimple_expression(simple_expression newSimple_expression)
  {
    if (newSimple_expression != simple_expression)
    {
      NotificationChain msgs = null;
      if (simple_expression != null)
        msgs = ((InternalEObject)simple_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION, null, msgs);
      if (newSimple_expression != null)
        msgs = ((InternalEObject)newSimple_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION, null, msgs);
      msgs = basicSetSimple_expression(newSimple_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION, newSimple_expression, newSimple_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public simple_expression getLogical_or_expression()
  {
    return logical_or_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLogical_or_expression(simple_expression newLogical_or_expression, NotificationChain msgs)
  {
    simple_expression oldLogical_or_expression = logical_or_expression;
    logical_or_expression = newLogical_or_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION, oldLogical_or_expression, newLogical_or_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLogical_or_expression(simple_expression newLogical_or_expression)
  {
    if (newLogical_or_expression != logical_or_expression)
    {
      NotificationChain msgs = null;
      if (logical_or_expression != null)
        msgs = ((InternalEObject)logical_or_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION, null, msgs);
      if (newLogical_or_expression != null)
        msgs = ((InternalEObject)newLogical_or_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION, null, msgs);
      msgs = basicSetLogical_or_expression(newLogical_or_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION, newLogical_or_expression, newLogical_or_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public expression getExpression()
  {
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression(expression newExpression, NotificationChain msgs)
  {
    expression oldExpression = expression;
    expression = newExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION, oldExpression, newExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpression(expression newExpression)
  {
    if (newExpression != expression)
    {
      NotificationChain msgs = null;
      if (expression != null)
        msgs = ((InternalEObject)expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION, null, msgs);
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION, null, msgs);
      msgs = basicSetExpression(newExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION, newExpression, newExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public conditional_expression getConditional_expression()
  {
    return conditional_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConditional_expression(conditional_expression newConditional_expression, NotificationChain msgs)
  {
    conditional_expression oldConditional_expression = conditional_expression;
    conditional_expression = newConditional_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION, oldConditional_expression, newConditional_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConditional_expression(conditional_expression newConditional_expression)
  {
    if (newConditional_expression != conditional_expression)
    {
      NotificationChain msgs = null;
      if (conditional_expression != null)
        msgs = ((InternalEObject)conditional_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION, null, msgs);
      if (newConditional_expression != null)
        msgs = ((InternalEObject)newConditional_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION, null, msgs);
      msgs = basicSetConditional_expression(newConditional_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION, newConditional_expression, newConditional_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION:
        return basicSetSimple_expression(null, msgs);
      case MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION:
        return basicSetLogical_or_expression(null, msgs);
      case MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION:
        return basicSetExpression(null, msgs);
      case MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION:
        return basicSetConditional_expression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION:
        return getSimple_expression();
      case MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION:
        return getLogical_or_expression();
      case MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION:
        return getExpression();
      case MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION:
        return getConditional_expression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION:
        setSimple_expression((simple_expression)newValue);
        return;
      case MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION:
        setLogical_or_expression((simple_expression)newValue);
        return;
      case MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION:
        setExpression((expression)newValue);
        return;
      case MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION:
        setConditional_expression((conditional_expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION:
        setSimple_expression((simple_expression)null);
        return;
      case MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION:
        setLogical_or_expression((simple_expression)null);
        return;
      case MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION:
        setExpression((expression)null);
        return;
      case MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION:
        setConditional_expression((conditional_expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CONDITIONAL_EXPRESSION__SIMPLE_EXPRESSION:
        return simple_expression != null;
      case MyDslPackage.CONDITIONAL_EXPRESSION__LOGICAL_OR_EXPRESSION:
        return logical_or_expression != null;
      case MyDslPackage.CONDITIONAL_EXPRESSION__EXPRESSION:
        return expression != null;
      case MyDslPackage.CONDITIONAL_EXPRESSION__CONDITIONAL_EXPRESSION:
        return conditional_expression != null;
    }
    return super.eIsSet(featureID);
  }

} //conditional_expressionImpl
