/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.declaration;
import org.xtext.example.mydsl.myDsl.declaration_specifiers;
import org.xtext.example.mydsl.myDsl.init_declarator_list;
import org.xtext.example.mydsl.myDsl.static_assert_declaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.declarationImpl#getDeclaration_specifiers <em>Declaration specifiers</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.declarationImpl#getInit_declarator_list <em>Init declarator list</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.declarationImpl#getStatic_assert_declaration <em>Static assert declaration</em>}</li>
 * </ul>
 *
 * @generated
 */
public class declarationImpl extends MinimalEObjectImpl.Container implements declaration
{
  /**
   * The cached value of the '{@link #getDeclaration_specifiers() <em>Declaration specifiers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaration_specifiers()
   * @generated
   * @ordered
   */
  protected declaration_specifiers declaration_specifiers;

  /**
   * The cached value of the '{@link #getInit_declarator_list() <em>Init declarator list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_declarator_list()
   * @generated
   * @ordered
   */
  protected init_declarator_list init_declarator_list;

  /**
   * The cached value of the '{@link #getStatic_assert_declaration() <em>Static assert declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatic_assert_declaration()
   * @generated
   * @ordered
   */
  protected static_assert_declaration static_assert_declaration;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected declarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public declaration_specifiers getDeclaration_specifiers()
  {
    return declaration_specifiers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDeclaration_specifiers(declaration_specifiers newDeclaration_specifiers, NotificationChain msgs)
  {
    declaration_specifiers oldDeclaration_specifiers = declaration_specifiers;
    declaration_specifiers = newDeclaration_specifiers;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS, oldDeclaration_specifiers, newDeclaration_specifiers);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDeclaration_specifiers(declaration_specifiers newDeclaration_specifiers)
  {
    if (newDeclaration_specifiers != declaration_specifiers)
    {
      NotificationChain msgs = null;
      if (declaration_specifiers != null)
        msgs = ((InternalEObject)declaration_specifiers).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS, null, msgs);
      if (newDeclaration_specifiers != null)
        msgs = ((InternalEObject)newDeclaration_specifiers).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS, null, msgs);
      msgs = basicSetDeclaration_specifiers(newDeclaration_specifiers, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS, newDeclaration_specifiers, newDeclaration_specifiers));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public init_declarator_list getInit_declarator_list()
  {
    return init_declarator_list;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInit_declarator_list(init_declarator_list newInit_declarator_list, NotificationChain msgs)
  {
    init_declarator_list oldInit_declarator_list = init_declarator_list;
    init_declarator_list = newInit_declarator_list;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST, oldInit_declarator_list, newInit_declarator_list);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInit_declarator_list(init_declarator_list newInit_declarator_list)
  {
    if (newInit_declarator_list != init_declarator_list)
    {
      NotificationChain msgs = null;
      if (init_declarator_list != null)
        msgs = ((InternalEObject)init_declarator_list).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST, null, msgs);
      if (newInit_declarator_list != null)
        msgs = ((InternalEObject)newInit_declarator_list).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST, null, msgs);
      msgs = basicSetInit_declarator_list(newInit_declarator_list, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST, newInit_declarator_list, newInit_declarator_list));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static_assert_declaration getStatic_assert_declaration()
  {
    return static_assert_declaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStatic_assert_declaration(static_assert_declaration newStatic_assert_declaration, NotificationChain msgs)
  {
    static_assert_declaration oldStatic_assert_declaration = static_assert_declaration;
    static_assert_declaration = newStatic_assert_declaration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION, oldStatic_assert_declaration, newStatic_assert_declaration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStatic_assert_declaration(static_assert_declaration newStatic_assert_declaration)
  {
    if (newStatic_assert_declaration != static_assert_declaration)
    {
      NotificationChain msgs = null;
      if (static_assert_declaration != null)
        msgs = ((InternalEObject)static_assert_declaration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION, null, msgs);
      if (newStatic_assert_declaration != null)
        msgs = ((InternalEObject)newStatic_assert_declaration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION, null, msgs);
      msgs = basicSetStatic_assert_declaration(newStatic_assert_declaration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION, newStatic_assert_declaration, newStatic_assert_declaration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS:
        return basicSetDeclaration_specifiers(null, msgs);
      case MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST:
        return basicSetInit_declarator_list(null, msgs);
      case MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION:
        return basicSetStatic_assert_declaration(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS:
        return getDeclaration_specifiers();
      case MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST:
        return getInit_declarator_list();
      case MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION:
        return getStatic_assert_declaration();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS:
        setDeclaration_specifiers((declaration_specifiers)newValue);
        return;
      case MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST:
        setInit_declarator_list((init_declarator_list)newValue);
        return;
      case MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION:
        setStatic_assert_declaration((static_assert_declaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS:
        setDeclaration_specifiers((declaration_specifiers)null);
        return;
      case MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST:
        setInit_declarator_list((init_declarator_list)null);
        return;
      case MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION:
        setStatic_assert_declaration((static_assert_declaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DECLARATION__DECLARATION_SPECIFIERS:
        return declaration_specifiers != null;
      case MyDslPackage.DECLARATION__INIT_DECLARATOR_LIST:
        return init_declarator_list != null;
      case MyDslPackage.DECLARATION__STATIC_ASSERT_DECLARATION:
        return static_assert_declaration != null;
    }
    return super.eIsSet(featureID);
  }

} //declarationImpl
