/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.declaration;
import org.xtext.example.mydsl.myDsl.external_declaration;
import org.xtext.example.mydsl.myDsl.function_definition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>external declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.external_declarationImpl#getFunction_definition <em>Function definition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.external_declarationImpl#getDeclaration <em>Declaration</em>}</li>
 * </ul>
 *
 * @generated
 */
public class external_declarationImpl extends MinimalEObjectImpl.Container implements external_declaration
{
  /**
   * The cached value of the '{@link #getFunction_definition() <em>Function definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunction_definition()
   * @generated
   * @ordered
   */
  protected function_definition function_definition;

  /**
   * The cached value of the '{@link #getDeclaration() <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaration()
   * @generated
   * @ordered
   */
  protected declaration declaration;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected external_declarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXTERNAL_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public function_definition getFunction_definition()
  {
    return function_definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFunction_definition(function_definition newFunction_definition, NotificationChain msgs)
  {
    function_definition oldFunction_definition = function_definition;
    function_definition = newFunction_definition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION, oldFunction_definition, newFunction_definition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFunction_definition(function_definition newFunction_definition)
  {
    if (newFunction_definition != function_definition)
    {
      NotificationChain msgs = null;
      if (function_definition != null)
        msgs = ((InternalEObject)function_definition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION, null, msgs);
      if (newFunction_definition != null)
        msgs = ((InternalEObject)newFunction_definition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION, null, msgs);
      msgs = basicSetFunction_definition(newFunction_definition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION, newFunction_definition, newFunction_definition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public declaration getDeclaration()
  {
    return declaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDeclaration(declaration newDeclaration, NotificationChain msgs)
  {
    declaration oldDeclaration = declaration;
    declaration = newDeclaration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXTERNAL_DECLARATION__DECLARATION, oldDeclaration, newDeclaration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDeclaration(declaration newDeclaration)
  {
    if (newDeclaration != declaration)
    {
      NotificationChain msgs = null;
      if (declaration != null)
        msgs = ((InternalEObject)declaration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXTERNAL_DECLARATION__DECLARATION, null, msgs);
      if (newDeclaration != null)
        msgs = ((InternalEObject)newDeclaration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXTERNAL_DECLARATION__DECLARATION, null, msgs);
      msgs = basicSetDeclaration(newDeclaration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXTERNAL_DECLARATION__DECLARATION, newDeclaration, newDeclaration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION:
        return basicSetFunction_definition(null, msgs);
      case MyDslPackage.EXTERNAL_DECLARATION__DECLARATION:
        return basicSetDeclaration(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION:
        return getFunction_definition();
      case MyDslPackage.EXTERNAL_DECLARATION__DECLARATION:
        return getDeclaration();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION:
        setFunction_definition((function_definition)newValue);
        return;
      case MyDslPackage.EXTERNAL_DECLARATION__DECLARATION:
        setDeclaration((declaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION:
        setFunction_definition((function_definition)null);
        return;
      case MyDslPackage.EXTERNAL_DECLARATION__DECLARATION:
        setDeclaration((declaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXTERNAL_DECLARATION__FUNCTION_DEFINITION:
        return function_definition != null;
      case MyDslPackage.EXTERNAL_DECLARATION__DECLARATION:
        return declaration != null;
    }
    return super.eIsSet(featureID);
  }

} //external_declarationImpl
