/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.imaginaryType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>imaginary Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.imaginaryTypeImpl#getImaginary_type <em>Imaginary type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class imaginaryTypeImpl extends type_specifierImpl implements imaginaryType
{
  /**
   * The default value of the '{@link #getImaginary_type() <em>Imaginary type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImaginary_type()
   * @generated
   * @ordered
   */
  protected static final String IMAGINARY_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getImaginary_type() <em>Imaginary type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImaginary_type()
   * @generated
   * @ordered
   */
  protected String imaginary_type = IMAGINARY_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected imaginaryTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.IMAGINARY_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getImaginary_type()
  {
    return imaginary_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setImaginary_type(String newImaginary_type)
  {
    String oldImaginary_type = imaginary_type;
    imaginary_type = newImaginary_type;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.IMAGINARY_TYPE__IMAGINARY_TYPE, oldImaginary_type, imaginary_type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.IMAGINARY_TYPE__IMAGINARY_TYPE:
        return getImaginary_type();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.IMAGINARY_TYPE__IMAGINARY_TYPE:
        setImaginary_type((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.IMAGINARY_TYPE__IMAGINARY_TYPE:
        setImaginary_type(IMAGINARY_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.IMAGINARY_TYPE__IMAGINARY_TYPE:
        return IMAGINARY_TYPE_EDEFAULT == null ? imaginary_type != null : !IMAGINARY_TYPE_EDEFAULT.equals(imaginary_type);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (imaginary_type: ");
    result.append(imaginary_type);
    result.append(')');
    return result.toString();
  }

} //imaginaryTypeImpl
