/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.init_declarator;
import org.xtext.example.mydsl.myDsl.init_declarator_list2;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>init declarator list2</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.init_declarator_list2Impl#getInit_declarator <em>Init declarator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.init_declarator_list2Impl#getInit_declarator_list2 <em>Init declarator list2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class init_declarator_list2Impl extends MinimalEObjectImpl.Container implements init_declarator_list2
{
  /**
   * The cached value of the '{@link #getInit_declarator() <em>Init declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_declarator()
   * @generated
   * @ordered
   */
  protected init_declarator init_declarator;

  /**
   * The cached value of the '{@link #getInit_declarator_list2() <em>Init declarator list2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_declarator_list2()
   * @generated
   * @ordered
   */
  protected init_declarator_list2 init_declarator_list2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected init_declarator_list2Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INIT_DECLARATOR_LIST2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public init_declarator getInit_declarator()
  {
    return init_declarator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInit_declarator(init_declarator newInit_declarator, NotificationChain msgs)
  {
    init_declarator oldInit_declarator = init_declarator;
    init_declarator = newInit_declarator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR, oldInit_declarator, newInit_declarator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInit_declarator(init_declarator newInit_declarator)
  {
    if (newInit_declarator != init_declarator)
    {
      NotificationChain msgs = null;
      if (init_declarator != null)
        msgs = ((InternalEObject)init_declarator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR, null, msgs);
      if (newInit_declarator != null)
        msgs = ((InternalEObject)newInit_declarator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR, null, msgs);
      msgs = basicSetInit_declarator(newInit_declarator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR, newInit_declarator, newInit_declarator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public init_declarator_list2 getInit_declarator_list2()
  {
    return init_declarator_list2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInit_declarator_list2(init_declarator_list2 newInit_declarator_list2, NotificationChain msgs)
  {
    init_declarator_list2 oldInit_declarator_list2 = init_declarator_list2;
    init_declarator_list2 = newInit_declarator_list2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2, oldInit_declarator_list2, newInit_declarator_list2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInit_declarator_list2(init_declarator_list2 newInit_declarator_list2)
  {
    if (newInit_declarator_list2 != init_declarator_list2)
    {
      NotificationChain msgs = null;
      if (init_declarator_list2 != null)
        msgs = ((InternalEObject)init_declarator_list2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2, null, msgs);
      if (newInit_declarator_list2 != null)
        msgs = ((InternalEObject)newInit_declarator_list2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2, null, msgs);
      msgs = basicSetInit_declarator_list2(newInit_declarator_list2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2, newInit_declarator_list2, newInit_declarator_list2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR:
        return basicSetInit_declarator(null, msgs);
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2:
        return basicSetInit_declarator_list2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR:
        return getInit_declarator();
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2:
        return getInit_declarator_list2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR:
        setInit_declarator((init_declarator)newValue);
        return;
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2:
        setInit_declarator_list2((init_declarator_list2)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR:
        setInit_declarator((init_declarator)null);
        return;
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2:
        setInit_declarator_list2((init_declarator_list2)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR:
        return init_declarator != null;
      case MyDslPackage.INIT_DECLARATOR_LIST2__INIT_DECLARATOR_LIST2:
        return init_declarator_list2 != null;
    }
    return super.eIsSet(featureID);
  }

} //init_declarator_list2Impl
