/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.additive_expression;
import org.xtext.example.mydsl.myDsl.shift_expression;
import org.xtext.example.mydsl.myDsl.shift_expression2;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>shift expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.shift_expressionImpl#getAdditive_expression <em>Additive expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.shift_expressionImpl#getShift_expression2 <em>Shift expression2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class shift_expressionImpl extends MinimalEObjectImpl.Container implements shift_expression
{
  /**
   * The cached value of the '{@link #getAdditive_expression() <em>Additive expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdditive_expression()
   * @generated
   * @ordered
   */
  protected additive_expression additive_expression;

  /**
   * The cached value of the '{@link #getShift_expression2() <em>Shift expression2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShift_expression2()
   * @generated
   * @ordered
   */
  protected shift_expression2 shift_expression2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected shift_expressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SHIFT_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public additive_expression getAdditive_expression()
  {
    return additive_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAdditive_expression(additive_expression newAdditive_expression, NotificationChain msgs)
  {
    additive_expression oldAdditive_expression = additive_expression;
    additive_expression = newAdditive_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION, oldAdditive_expression, newAdditive_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdditive_expression(additive_expression newAdditive_expression)
  {
    if (newAdditive_expression != additive_expression)
    {
      NotificationChain msgs = null;
      if (additive_expression != null)
        msgs = ((InternalEObject)additive_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION, null, msgs);
      if (newAdditive_expression != null)
        msgs = ((InternalEObject)newAdditive_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION, null, msgs);
      msgs = basicSetAdditive_expression(newAdditive_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION, newAdditive_expression, newAdditive_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public shift_expression2 getShift_expression2()
  {
    return shift_expression2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetShift_expression2(shift_expression2 newShift_expression2, NotificationChain msgs)
  {
    shift_expression2 oldShift_expression2 = shift_expression2;
    shift_expression2 = newShift_expression2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2, oldShift_expression2, newShift_expression2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setShift_expression2(shift_expression2 newShift_expression2)
  {
    if (newShift_expression2 != shift_expression2)
    {
      NotificationChain msgs = null;
      if (shift_expression2 != null)
        msgs = ((InternalEObject)shift_expression2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2, null, msgs);
      if (newShift_expression2 != null)
        msgs = ((InternalEObject)newShift_expression2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2, null, msgs);
      msgs = basicSetShift_expression2(newShift_expression2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2, newShift_expression2, newShift_expression2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION:
        return basicSetAdditive_expression(null, msgs);
      case MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2:
        return basicSetShift_expression2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION:
        return getAdditive_expression();
      case MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2:
        return getShift_expression2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION:
        setAdditive_expression((additive_expression)newValue);
        return;
      case MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2:
        setShift_expression2((shift_expression2)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION:
        setAdditive_expression((additive_expression)null);
        return;
      case MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2:
        setShift_expression2((shift_expression2)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SHIFT_EXPRESSION__ADDITIVE_EXPRESSION:
        return additive_expression != null;
      case MyDslPackage.SHIFT_EXPRESSION__SHIFT_EXPRESSION2:
        return shift_expression2 != null;
    }
    return super.eIsSet(featureID);
  }

} //shift_expressionImpl
