/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.storage_class_specifier;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>storage class specifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.storage_class_specifierImpl#getTypedef <em>Typedef</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.storage_class_specifierImpl#getExtern <em>Extern</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.storage_class_specifierImpl#getStatic <em>Static</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.storage_class_specifierImpl#getThread_local <em>Thread local</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.storage_class_specifierImpl#getAuto <em>Auto</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.storage_class_specifierImpl#getRegister <em>Register</em>}</li>
 * </ul>
 *
 * @generated
 */
public class storage_class_specifierImpl extends MinimalEObjectImpl.Container implements storage_class_specifier
{
  /**
   * The default value of the '{@link #getTypedef() <em>Typedef</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypedef()
   * @generated
   * @ordered
   */
  protected static final String TYPEDEF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTypedef() <em>Typedef</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypedef()
   * @generated
   * @ordered
   */
  protected String typedef = TYPEDEF_EDEFAULT;

  /**
   * The default value of the '{@link #getExtern() <em>Extern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtern()
   * @generated
   * @ordered
   */
  protected static final String EXTERN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getExtern() <em>Extern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtern()
   * @generated
   * @ordered
   */
  protected String extern = EXTERN_EDEFAULT;

  /**
   * The default value of the '{@link #getStatic() <em>Static</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatic()
   * @generated
   * @ordered
   */
  protected static final String STATIC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStatic() <em>Static</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatic()
   * @generated
   * @ordered
   */
  protected String static_ = STATIC_EDEFAULT;

  /**
   * The default value of the '{@link #getThread_local() <em>Thread local</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThread_local()
   * @generated
   * @ordered
   */
  protected static final String THREAD_LOCAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getThread_local() <em>Thread local</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThread_local()
   * @generated
   * @ordered
   */
  protected String thread_local = THREAD_LOCAL_EDEFAULT;

  /**
   * The default value of the '{@link #getAuto() <em>Auto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuto()
   * @generated
   * @ordered
   */
  protected static final String AUTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAuto() <em>Auto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuto()
   * @generated
   * @ordered
   */
  protected String auto = AUTO_EDEFAULT;

  /**
   * The default value of the '{@link #getRegister() <em>Register</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegister()
   * @generated
   * @ordered
   */
  protected static final String REGISTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRegister() <em>Register</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegister()
   * @generated
   * @ordered
   */
  protected String register = REGISTER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected storage_class_specifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.STORAGE_CLASS_SPECIFIER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTypedef()
  {
    return typedef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypedef(String newTypedef)
  {
    String oldTypedef = typedef;
    typedef = newTypedef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STORAGE_CLASS_SPECIFIER__TYPEDEF, oldTypedef, typedef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getExtern()
  {
    return extern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExtern(String newExtern)
  {
    String oldExtern = extern;
    extern = newExtern;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STORAGE_CLASS_SPECIFIER__EXTERN, oldExtern, extern));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStatic()
  {
    return static_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStatic(String newStatic)
  {
    String oldStatic = static_;
    static_ = newStatic;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STORAGE_CLASS_SPECIFIER__STATIC, oldStatic, static_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getThread_local()
  {
    return thread_local;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setThread_local(String newThread_local)
  {
    String oldThread_local = thread_local;
    thread_local = newThread_local;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STORAGE_CLASS_SPECIFIER__THREAD_LOCAL, oldThread_local, thread_local));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAuto()
  {
    return auto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAuto(String newAuto)
  {
    String oldAuto = auto;
    auto = newAuto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STORAGE_CLASS_SPECIFIER__AUTO, oldAuto, auto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getRegister()
  {
    return register;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRegister(String newRegister)
  {
    String oldRegister = register;
    register = newRegister;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STORAGE_CLASS_SPECIFIER__REGISTER, oldRegister, register));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__TYPEDEF:
        return getTypedef();
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__EXTERN:
        return getExtern();
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__STATIC:
        return getStatic();
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__THREAD_LOCAL:
        return getThread_local();
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__AUTO:
        return getAuto();
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__REGISTER:
        return getRegister();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__TYPEDEF:
        setTypedef((String)newValue);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__EXTERN:
        setExtern((String)newValue);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__STATIC:
        setStatic((String)newValue);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__THREAD_LOCAL:
        setThread_local((String)newValue);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__AUTO:
        setAuto((String)newValue);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__REGISTER:
        setRegister((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__TYPEDEF:
        setTypedef(TYPEDEF_EDEFAULT);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__EXTERN:
        setExtern(EXTERN_EDEFAULT);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__STATIC:
        setStatic(STATIC_EDEFAULT);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__THREAD_LOCAL:
        setThread_local(THREAD_LOCAL_EDEFAULT);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__AUTO:
        setAuto(AUTO_EDEFAULT);
        return;
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__REGISTER:
        setRegister(REGISTER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__TYPEDEF:
        return TYPEDEF_EDEFAULT == null ? typedef != null : !TYPEDEF_EDEFAULT.equals(typedef);
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__EXTERN:
        return EXTERN_EDEFAULT == null ? extern != null : !EXTERN_EDEFAULT.equals(extern);
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__STATIC:
        return STATIC_EDEFAULT == null ? static_ != null : !STATIC_EDEFAULT.equals(static_);
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__THREAD_LOCAL:
        return THREAD_LOCAL_EDEFAULT == null ? thread_local != null : !THREAD_LOCAL_EDEFAULT.equals(thread_local);
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__AUTO:
        return AUTO_EDEFAULT == null ? auto != null : !AUTO_EDEFAULT.equals(auto);
      case MyDslPackage.STORAGE_CLASS_SPECIFIER__REGISTER:
        return REGISTER_EDEFAULT == null ? register != null : !REGISTER_EDEFAULT.equals(register);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (typedef: ");
    result.append(typedef);
    result.append(", extern: ");
    result.append(extern);
    result.append(", static: ");
    result.append(static_);
    result.append(", thread_local: ");
    result.append(thread_local);
    result.append(", auto: ");
    result.append(auto);
    result.append(", register: ");
    result.append(register);
    result.append(')');
    return result.toString();
  }

} //storage_class_specifierImpl
