/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.unsignedType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>unsigned Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.unsignedTypeImpl#getUnsigned_type <em>Unsigned type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class unsignedTypeImpl extends type_specifierImpl implements unsignedType
{
  /**
   * The default value of the '{@link #getUnsigned_type() <em>Unsigned type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnsigned_type()
   * @generated
   * @ordered
   */
  protected static final String UNSIGNED_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUnsigned_type() <em>Unsigned type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnsigned_type()
   * @generated
   * @ordered
   */
  protected String unsigned_type = UNSIGNED_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected unsignedTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.UNSIGNED_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUnsigned_type()
  {
    return unsigned_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnsigned_type(String newUnsigned_type)
  {
    String oldUnsigned_type = unsigned_type;
    unsigned_type = newUnsigned_type;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.UNSIGNED_TYPE__UNSIGNED_TYPE, oldUnsigned_type, unsigned_type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.UNSIGNED_TYPE__UNSIGNED_TYPE:
        return getUnsigned_type();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.UNSIGNED_TYPE__UNSIGNED_TYPE:
        setUnsigned_type((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.UNSIGNED_TYPE__UNSIGNED_TYPE:
        setUnsigned_type(UNSIGNED_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.UNSIGNED_TYPE__UNSIGNED_TYPE:
        return UNSIGNED_TYPE_EDEFAULT == null ? unsigned_type != null : !UNSIGNED_TYPE_EDEFAULT.equals(unsigned_type);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (unsigned_type: ");
    result.append(unsigned_type);
    result.append(')');
    return result.toString();
  }

} //unsignedTypeImpl
